In [1]:
#broadcasting: a set of rules which lets you apply binary operations between arrays of different sizes and shapes
import numpy as np


In [3]:
# for arrays of the same size, binary operations performed on an element by element basis
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [4]:
# broadcasting allows for different sizes
a + 5

array([5, 6, 7])

In [6]:
# a is stretched/broadcasted across m
# matches the shape of M
m = np.ones((3, 3))
m + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
# stretch both a and b to a common shape
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
a * b

array([[0],
       [1],
       [2]])

In [8]:
# rules of broadcasting
# 1) if the two arrays differ in their number of dimenions, the shape of the one with the fewer
# dimensions is padded with ones on its leading left side
# 2) if the shape of the two ararys does not match in any dimension, the array with shape equal to 1 in that
# dimension is stretched to match the other shape
# 3) if in any dimension the sizes disagree and neither is equal to 1, an error is raised

In [13]:
# add a 2D and 1D array
m = np.ones((2, 3)) # shape is (2, 3)
a = np.arange(3) # shape is (3,)

# by rule 1, a has fewer dimensions so we pad it on the left with ones
# a.shape becomes (1, 3)
# by rule 2, the first dimension disagrees so we stretch it
# a.shape becomes (2, 3)
# the shapes now match and the final shape will be (2, 3)

array([[1., 2., 3.],
       [1., 2., 3.]])

In [16]:
# example where both need to be broadcast
a = np.arange(3).reshape((3, 1)) # shape is (3, 1)
b = np.arange(3) # shape is (3, )

# by rule one, we must pad b
# b now becomes (1, 3)
# by rule 2, upgrade each of the ones
# b now becomes (3, 3) and a becomes (3, 3)
# the shapes are now compatible
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [17]:
# an example where they are not compatible
m = np.ones((3, 2)) # shape is (3, 2)
a = np.arange(3) # shape is (3,)

# rule 1 is that we must pad a
# a now becomes (1, 3)
# rule 2 is that we have to stretch
# a now becomes (3, 3)
# the final shapes do not match, so these are incompatible

In [18]:
# broadcasting in practice

# centering an array
rng = np.random.default_rng(seed=1701)
X = rng.random((10, 3))
Xmean = X.mean(0)
X_centered = X - Xmean
