In [1]:
# The Basics of NumPy Arrays

In [2]:
import numpy as np # default import
rng = np.random.default_rng(seed = 1701) # sets a seed for reproducibility, same random arrays will be generated

x1 = rng.integers(10, size=6) # one dimensional array
x2 = rng.integers(10, size=(3, 4)) # two dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three dimensional array
print("x1: ", x1)
print("x2: ", x2)
print("x3: ", x3)

## each array has various properties
# ndim: the number of dimensions
# shape: the size of each dimension
# size: the total size of the array
# dtype: the type of each element
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)

x1:  [9 4 0 3 8 6]
x2:  [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
x3:  [[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64


In [3]:
# indexing is similar to normal python
# in one dimensional array, can just use ith index to access
x1[0]
x1[4]
x1[-1] # index from the end

# multidimensonal arrays accessed using comma separated tuple
x2[0, 0]
x2[2, -1]
x2[0, 0] = 12 # can also be modified

In [7]:
# can also do slicing in the same way as python
# x[start:stop:step]

x1[:3] # first 3 elements
x1[3:] # all elements after index 3
x1[1:4] # middle subarary
x1[::2] # every second element

x2[:2, :3] # first two twos & three columns
x2[:3, ::2] # three rows, every second column

#commonly need to access single rows or columns
x2[:, 0] # first column of x2
x2[0, :] # first row of x2

array([3, 1, 3, 7])

In [9]:
# numpy arrays slives are returned as views rather than copies
# modifying a slice will modify the original
x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99
x2


array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [10]:
# can still copy arrays or subarrays with the "copy" method
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy = 100 # will not modify the original

In [12]:
# reshapng arrays can be done with the "reshape" method
# size of initial array much match the size of the reshaped array
# will return no copy view of the original array
grid = np.arange(1, 10).reshape(3, 3) # turns sequence of 1-9 into 3x3 array

# common operation is converting 1D array into two dimensional row/column matrix
x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape
x.reshape((3, 1)) # column vector via reshape

# shorthand is to use "np.newaxis" in the slicing syntax
x[np.newaxis, :] # row vector via newaxis
x[:, np.newaxis] # column vector via newaxis

array([[1],
       [2],
       [3]])

In [26]:
# can combine multiple arrays into one or split one up
# concatination is accomplised using "np.concatenate, np.vstack, np.hstack"
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) # concatenate x and y togeter

z = np.array([99, 99, 99])
np.concatenate([x, y, z]) # can concatenate multiple at once

# can be used for 2D arrays
grid = np.arange(1, 7).reshape(2, 3)
np.concatenate([grid, grid]) # concatenate along the first axis
np.concatenate([grid, grid], axis = 1) # concatenate along the second axis

# for arrays of mixed dimensions, it can be easier to use "np.vstack" and "np.hstack"
np.vstack([x, grid]) # vertically stack the arrays

y = np.array([[99], [99]])
np.hstack([grid, y]) # horizontally stack the arrays

# for higher dimension, "np.dstack" will stack along third axis

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [1]:
# can split arrays with "np.split, np.hsplit, np.vsplit"
# pass a list of indicies giving the split points
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [3, 5])

# n split points leads to n + 1 subarrays

grid = np.arange(16).reshape(4, 4)
upper, lower = np.vsplit(grid, [2]) # split in half vertically
left, right = np.hsplit(grid, [2]) # split in half horizontally

NameError: name 'np' is not defined

In [14]:
# experiementing
rng = np.random.default_rng(seed=100) # make an rng
a = rng.integers(10, size = 10) # make 10 random integers

# can index the normal way
a[1]
a[3:5]
a[-1]

b = a[3:5] # this will make a view not a copy
b[0] = 1000 # this will modify both a and b
c = a[3:5].copy() # have to call copy if we want a copy
c[0] = -1 # this will not modify a or b 

# can reshape matricies
x = np.arange(1,10).reshape((3, 3))

# can concatenate arrays togeter
x = np.arange(10)
y = np.arange(10)
np.concatenate([x, y])

# the main takeaways of this chapter is just simple numpy array manipulation
# we see that we can index it like a normal python array and that we must do deep copies
# otherwise we just get a view that references the original. We can also reshape matricies 
# into different formats/dimensions. Overall basic numpy array manipulation

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])