In [4]:
# Chapter 9: Comparisons, Masks, Boolean Logic
# can use boolean masks to examine and manipulate values in numpy arrays
# masking used when you want to extract, modify, count or manipulate values based on some criterion
import numpy as np

In [7]:
# numpy implements comparison operators and the result is an array with a boolean data type
x = np.array([1, 2, 3, 4, 5])

# will all return an array of boolean values for each element in the operated list
x < 3    # np.less()
x > 3    # n.greater()
x <= 3   # np.less_equal()
x >= 3   # np.greater_equal()
x != 3   # np.not_equal()
x == 3   # np.equal()

# can do element wise comparison of two arrays
(x * 2) == (x ** 2)

array([False,  True, False, False, False])

In [9]:
# work on arrays of any size and shape
rng = np.random.default_rng(seed = 1701)
x = rng.integers(10, size = (3, 4))

x < 6

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

In [10]:
# host of useful operations with boolean array
np.count_nonzero(x < 6) # count how many values are less than 6
np.sum(x < 6) # another way to count how many values are less than 6
np.sum(x < 6, axis = 1) # how many values less than 6 in each row
np.any(x > 8) # are there any values greater than 8
np.any(x < 0) # are there any values less than 0
np.all(x < 10) # are all the values less than 10
np.all(x == 6) # are all the values equal to 6

# np.all and np.any can be used along particular axes as well
np.all(x < 8, axis = 1) # are all values in each row less than 8

array([False, False,  True])

In [11]:
# can also use bitwise operators with boolean arrays 
# &, |, ^, ~

In [14]:
# can use boolean arrays as masks
x[x<5] # make a boolean array with x < 5 and then use that as a mask to get all values less than 5

array([4, 0, 3, 3, 1, 3, 4, 0])

In [ ]:
# keyword and/or vs operator &/|
# and and or operate on the object as a whole, treat object as single boolean entity
# all nonzero integers will evaluate as true
bool(42), bool(0)
bool(42 and 0)
bool(42 or 0)

# & and | operate on the elements within an object
# operates on the bitwise representation applying and and or to individual bits
bin(42)
bin(59)
bin(42 & 59)
bin(42 | 59)

# in numpy when you have a boolean array, thing of it as a string of bits where 1 = True and 0 = False
# and & and | will operate similarily to the preceeding example
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

x = np.arange(10)
(x > 4) & (x < 8) # dont use and