In [1]:
# standard python implementation is written in C
# each object is a pointer to a structure
# for example, the underlying structure for a long
# struct _longobject {
#   long ob_refcnt;        -> a reference count that helps python handle memory allocation and deallocation
#   PyTypeObject *ob_type; -> encodes the type of the variable
#   size_t ob_size;        -> specifies the size of the following data member
#   long ob_digit[1];      -> contains the actual interger value that we expect the python variable to represent
#};
# the way the object is stored leads to some additional overhead
# the difference?
#   a C integer is essentially a label for a position in memory whose bytes encode the integer value
#   a python integer is a pointer to a position in memory containing all the python object information 

In [5]:
L = list(range(10)) # a python list of the same object is more efficient, numpy style array
l2 = [True, "2", 0, 4.0] # a python list of mulitple objects is more dynamic but requires much more overhead and storage

In [4]:
# can use a fixed type data buffer from teh array module to create dense arrays of a uniform type
import array
L = list(range(10))
A = array.array('i', L); # i is a type code indicating the contents are integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#numpy adds efficiennt operations onto array based data
import numpy as np
# integer array
a = np.array([1, 2, 3])
print(a)

# numpy arrays can only contain data of the same type
# if they do not match, then numpy will upcast them 
b = np.array([3.14, 4, 2])
print(b)

# can explicitly set the type using the "dtype" keyword
c = np.array([1, 2, 3], dtype=np.float32)
print(c)

# numpy arrays can be multi-dimensional
d = np.array([range(i, i+3) for i in [2, 4, 6]])
print(d)

[1 2 3]
[3.14 4.   2.  ]
[1. 2. 3.]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [14]:
# for larger arrays, it is more efficinet to creat them from scratch using numpy routines

# create 1-D list of 10 zeros
a = np.zeros(10, dtype=int)
print(a)

# create 3x5 flaot point array with ones
b = np.ones((3, 5), dtype=float)
print(b)

# create 3x5 array fillwed with 3.14
c = np.full((3, 5), 3.14)
print(c)

# create array filled with linear sequence
# starting at 0 and ending at 20 going by 2's
d = np.arange(0, 20, 2)
print(d)

# create array of 5 values evenly spaved between 0 and 1
e = np.linspace(0, 1, 5)
print(e)

# create 3x3 array of uniformly distributed random values between 0 and 1
f = np.random.random((3, 3))
print(f)

# create 3x3 array of normally distributed random vals with mean 0 and std 1
e = np.random.normal(0, 1, (3, 3))
print(e)

# create 3x3 array of random ints in interval [0, 10)
f = np.random.randint(0, 10, (3, 3))
print(f)

# create 3x3 identity matrix
g = np.eye(3)
print(g)

# create uninitialized array of 3 ints
# vals will be whatever was at the mem location
h = np.empty(3)
print(h)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.69235603 0.77216514 0.98966568]
 [0.32947915 0.94094114 0.85733684]
 [0.18424776 0.49611096 0.73720758]]
[[ 0.18481896  1.10577518 -1.12495307]
 [-0.8798281  -0.66744599 -0.03441431]
 [ 0.68934705  0.16117577  0.81413327]]
[[5 7 4]
 [1 6 3]
 [1 8 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [3]:

# all the data types in numpy, can be specified in a string 
'''
bool_ Boolean (True or False) stored as a byte
int_ Default integer type (same as C long ; normally either int64 or int32 )
intc Identical to C int (normally int32 or int64 )
intp Integer used for indexing (same as C ssize_t ; normally either int32 or int64 )
int8 Byte (–128 to 127)
int16 Integer (–32768 to 32767)
int32 Integer (–2147483648 to 2147483647)
int64 Integer (–9223372036854775808 to 9223372036854775807)
uint8 Unsigned integer (0 to 255)
uint16 Unsigned integer (0 to 65535)
uint32 Unsigned integer (0 to 4294967295)
uint64 Unsigned integer (0 to 18446744073709551615)
float_ Shorthand for float64
float16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_ Shorthand for complex128
complex64 Complex number, represented by two 32-bit floats
complex128 Complex number, represented by two 64-bit floats
'''

'\nbool_ Boolean (True or False) stored as a byte\nint_ Default integer type (same as C long ; normally either int64 or int32 )\nintc Identical to C int (normally int32 or int64 )\nintp Integer used for indexing (same as C ssize_t ; normally either int32 or int64 )\nint8 Byte (–128 to 127)\nint16 Integer (–32768 to 32767)\nint32 Integer (–2147483648 to 2147483647)\nint64 Integer (–9223372036854775808 to 9223372036854775807)\nuint8 Unsigned integer (0 to 255)\nuint16 Unsigned integer (0 to 65535)\nuint32 Unsigned integer (0 to 4294967295)\nuint64 Unsigned integer (0 to 18446744073709551615)\nfloat_ Shorthand for float64\nfloat16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa\nfloat32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa\nfloat64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa\ncomplex_ Shorthand for complex128\ncomplex64 Complex number, represented by two 32-bit floats\ncomplex128 Complex number, represented by two 6

In [16]:
# experimenting
import numpy as np
a = np.array([1, 2, 3]) # just create a basic array
b = np.ones((3, 2)) # create a 3x2 matrix of ones
c = np.zeros((5, 5)) # create a 5x5 of zeros
d = np.zeros(10) # just create a 1d of 10 zeros
e = np.random.randint(0, 10, (3, 3)) # create a random matrix 
f = np.arange(3, 10, 2) # 3..10 with steps of 2

# not too much in this chapter, i think the biggest takeaway is just how to make the numpy arrays
# we can make arrays filled with ones, zeros, random numbers, or in a range upon many others

array([3, 5, 7, 9])